language: scala
services:
  - mongodb
jdk:
   - oraclejdk8
   - oraclejdk7
   - openjdk7
sbt_args: -no-colors
scala:
   - 2.11.6
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3260080e79f38bd09b5f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false